=== farlies/rsked/scripts/cooling_schema-1.1.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://rsked.org/cooling_schema1.1.json",
    "title": "cooling-1.1",
    "description": "Validates cooling configuration written in JSON with schema 1.1",
    "type": "object",
    "required": [ "encoding", "schema", "General" ],
    "additionalProperties" : false,
    "properties": {
        "encoding": { "const": "UTF-8" },
        "schema": { "const": "1.1" },
        "General" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "application" : { "const" : "cooling" },
                "version" : {"type" : "string" },
                "description" : {"type" : "string" },
                "poll_msec" : {"type" : "integer", "minimum" : 10 },
                "poll_trace" : {"type" : "integer", "minimum" : 1 }
            }
        },
        "Rsked" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "rsked_bin_path" : {"type" : "string"},
                "rsked_config_path" : {"type" : "string"},
                "rsked_debug" : {"type" : "boolean"},
                "kill_pattern" : {"type" : "string"},
                "mpd_stop_cmd" : {"type" : "string"}
            }
        },
        "Cooling" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "fan_gpio" : {"type" : "integer", "minimum" : 0},
                "sensor" : {"type" : "string"},
                "cool_start_temp" : {"type" : "number", "minimum" : 15},
                "cool_stop_temp" : {"type" : "number", "minimum" : 15},
                "min_cool_secs" : {"type" : "integer", "minimum" : 5}
            }
        },
        "SnoozeButton" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "button_gpio" : {"type" : "integer", "minimum" : 0}
            }
        },
        "PanelLEDs" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "red_gpio" : {"type" : "integer", "minimum" : 0},
                "green_gpio" : {"type" : "integer", "minimum" : 0}
            }
        }
    }
}

=== farlies/rsked/config/example-x86_64/rsked/example-cooling.json
{
    "encoding"   : "UTF-8",
    "schema"     : "1.1",

    "General" : {
        "application" : "cooling",
        "version"  : "2020-10-13T12:00",
        "description" : "for x86 workstation",
        "poll_msec"   : 1000,
        "poll_trace" : 300
    },

    "Rsked" : {
        "enabled" : true,
        "rsked_bin_path" : "~/bin/rsked",
        "rsked_config_path" : "~/.config/rsked/rsked.json",
        "rsked_debug" : false,
        "kill_pattern"   : "'ogg123|mpg321|gqrx|mpd'",
        "mpd_stop_cmd"   : "/usr/bin/mpc -p 6600 stop"
    },

    "Cooling" : {
        "enabled" : false,
        "fan_gpio" : 4,
        "sensor" : "/sys/class/thermal/thermal_zone0/temp",
        "cool_start_temp" : 55.0,
        "cool_stop_temp"  : 48.0,
        "min_cool_secs" : 301
    },

    "SnoozeButton" : {
        "enabled" : false,
        "button_gpio" : 18
    },

    "PanelLEDs" : {
        "enabled" : false,
        "green_gpio" : 17,
        "red_gpio" : 27
    }
}

=== farlies/rsked/config/example-armv7l/rsked/example-cooling.json
{
    "encoding"   : "UTF-8",
    "schema"     : "1.1",

    "General" : {
        "application" : "cooling",
        "version"  : "2022-12-30T14:00",
        "description" : "for RPi",
        "poll_msec"   : 1000,
        "poll_trace" : 300
    },

    "Rsked" : {
        "enabled" : true,
        "rsked_bin_path" : "~/bin/rsked",
        "rsked_config_path" : "~/.config/rsked/rsked.json",
        "rsked_debug" : false,
        "kill_pattern"   : "'ogg123|mpg321|gqrx|mpd'",
        "mpd_stop_cmd"   : "/usr/bin/mpc -p 6600 stop"
    },

    "Cooling" : {
        "enabled" : true,
        "fan_gpio" : 4,
        "sensor" : "/sys/class/thermal/thermal_zone0/temp",
        "cool_start_temp" : 65.0,
        "cool_stop_temp"  : 55.0,
        "min_cool_secs" : 301
    },

    "SnoozeButton" : {
        "enabled" : true,
        "button_gpio" : 18
    },

    "PanelLEDs" : {
        "enabled" : true,
        "green_gpio" : 17,
        "red_gpio" : 27
    }
}
