=== farlies/rsked/scripts/rsked_schema-1.2.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://rsked.org/rsked_schema2.json",
    "title": "rsked-1.2",
    "description": "Validates an rsked configuration written in JSON with schema 1.2",
    "type": "object",
    "required": [ "encoding", "schema" ],
    "additionalProperties" : false,
    "properties": {
        "encoding": { "const": "UTF-8" },
        "schema": { "const": "1.2" },
        "General" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "application" : { "type" : "string" },
                "version" : {"type" : "string" },
                "description" : {"type" : "string" },
                "sched_path" : {"type" : "string" }
            }
        },
        "Inet_checker" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "description" : {"type" : "string" },
                "refresh" : {"type" : "integer", "minimum" : 10 }
            }
        },
        "VU_monitor" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "description" : {"type" : "string" },
                "timeout" : {"type" : "integer", "minimum" : 10 },
                "bin_path" : {"type" : "string" }
            }
        },
        "Mpd_player" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "description" : {"type" : "string" },
                "debug" : {"type" : "boolean" },
                "run_mpd" : {"type" : "boolean" },
                "bin_path" : {"type" : "string" },
                "socket" : {"type" : "string" },
                "host" : {"type" : "string" },
                "port" : {"type" : "integer", "minimum" : 1 },
                "volume" : {"type" : "integer", "minimum" : 0, "maximum" : 100 }
            }
        },
        "Sdr_player" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "description" : {"type" : "string" },
                "bin_path" : {"type" : "string" },
                "work_conf" : {"type" : "string" },
                "gold_conf" : {"type" : "string" },
                "low_s" : {"type" : "number" },
                "low_low_s" : {"type" : "number" },
                "device_vendor" : {
                    "type" : "string",
                    "pattern" : "^[0-9A-Fa-f]{4}$"
                },
                "device_product" : {
                    "type" : "string",
                    "pattern" : "^[0-9A-Fa-f]{4}$"
                }
            }
        },
        "Vlc_player" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "description" : {"type" : "string" },
                "debug" : {"type" : "boolean" },
                "wait_us" : {"type" : "integer", "minimum" : 100 },
                "bin_path" : {"type" : "string" },
                "volume" : {"type" : "integer", "minimum" : 0, "maximum" : 100 }
            }
        },
        "Nrsc5_player" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "description" : {"type" : "string" },
                "device_index" : {"type" : "integer", "minimum" : 0 },
                "bin_path" : {"type" : "string" }
            }
        },
        "Ogg_player" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "description" : {"type" : "string" },
                "device_type" : {"enum" : ["alsa","pulse"] },
                "bin_path" : {"type" : "string" }
            }
        },
        "Mp3_player" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "description" : {"type" : "string" },
                "bin_path" : {"type" : "string" },
                "device_type" : {"enum" : ["alsa","oss"] }
            }
        },
        "player_preference" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "playlist" : {"type" : "object" },
                "directory" : {"type" : "object" },
                "file" : {"type" : "object" },
                "radio" : {"type" : "object" },
                "stream" : {"type" : "object" }
            }
        }
    }
}

=== farlies/rsked/test/tpmgr.json
{
    "encoding"   : "UTF-8",
    "schema" : "1.2",

    "General" : {
        "application" : "rsked",
        "sched_path" : "../test/sked-test1.json",
        "version" : "2022-03-30T15:45",
	"description" : "fake rsked.json using pathnames assumed to universally exist"
    },

    "Inet_checker" : {
        "enabled" : false,
        "refresh" : 60
    },

    "VU_monitor" : {
        "enabled" : false,
        "bin_path" : "/bin/sh",
        "timeout" : 40
    },

    "Mpd_player" : {
        "enabled" : false,
        "debug" : false,
        "run_mpd" : true,
        "bin_path" : "/bin/sh",
        "socket" : "/run/systemd/notify",
        "host" : "localhost",
        "port" : 6600,
        "volume" : 100
    },

    "Sdr_player" : {
        "enabled" : true,
        "bin_path"  : "/bin/sh",
        "work_conf"  : "/etc/hosts",
        "gold_conf"  : "/etc/hosts",
        "low_s"      : -20.0,
        "low_low_s"  : -40.0
    },

    "Vlc_player" : {
        "enabled" : true,
        "volume" : 100,
        "bin_path"   : "/bin/sh"
    },

    "Ogg_player" : {
        "enabled" : true,
        "device_type" : "alsa",
        "bin_path" : "/bin/sh"
    },

    "Mp3_player" : {
        "enabled" : false,
        "device_type" : "alsa",
        "bin_path"   : "/bin/sh"
    }
    
}

=== farlies/rsked/config/example-x86_64/rsked/example-rsked.json
{
    "encoding" : "UTF-8",
    "schema" : "1.2",

    "General" : {
        "application" : "rsked",
        "sched_path" : "~/.config/rsked/schedule.json",
        "version" : "2022-04-01T18:00",
        "description" : "example for 64-bit x86 Linux"
    },

    "Inet_checker" : {
        "enabled" : true,
        "refresh" : 60
    },

    "VU_monitor" : {
        "enabled" : true,
        "bin_path" : "~/bin/vumonitor",
        "timeout" : 40
    },

    "Vlc_player" : {
	"description" : "any player record may have a description string",
        "enabled" : false,
        "debug" : false,
        "bin_path" : "/usr/bin/vlc",
        "volume" : 100
    },

    "Mpd_player" : {
        "enabled" : true,
        "debug" : false,
        "run_mpd" : true,
        "bin_path" : "/usr/bin/mpd",
        "socket" : "/run/user/1000/mpd.socket",
        "host" : "localhost",
        "port" : 6600,
        "volume" : 100
    },

    "Nrsc5_player" : {
        "enabled" : true,
        "bin_path"  : "/usr/local/bin/nrsc5",
        "device_index" : 0
    },

    "Sdr_player" : {
        "enabled" : true,
        "bin_path"  : "~/bin/gqrx",
        "work_conf"  : "~/.config/gqrx/gqrx.conf",
        "gold_conf"  : "~/.config/gqrx/gold.conf",
        "low_s"      : -20.0,
        "low_low_s"  : -40.0,
        "device_vendor" : "0bda",
        "device_product" : "2838"
    },

    "Ogg_player" : {
        "enabled" : true,
        "device_type" : "alsa",
        "bin_path"   : "/usr/bin/ogg123"
    },

    "Mp3_player" : {
        "enabled" : true,
        "device_type" : "alsa",
        "bin_path"   : "/usr/bin/mpg321"
    }
}

=== farlies/rsked/test/tpmgr2.json
{
    "encoding"   : "UTF-8",
    "schema" : "1.2",

    "General" : {
        "application" : "rsked",
        "sched_path" : "~/.config/rsked/schedule.json",
        "version" : "2022-03-30T15:45",
	"description" : "alt rsked.json using pathnames assumed to universally exist"
    },

    "Inet_checker" : {
        "enabled" : false,
        "refresh" : 60
    },

    "VU_monitor" : {
        "enabled" : false,
        "bin_path" : "/bin/sh",
        "timeout" : 40
    },

    "player_preference" : {
        "directory" : {
            "mp3" : [ "Mpd_player", "Mp3_player" ],
            "ogg" : [ "Ogg_player", "Mpd_player" ]
        },
        "file" : {
            "mp3" : [ "Mp3_player", "Mpd_player" ],
            "ogg" : [ "Ogg_player", "Mpd_player" ]
        }
    },

    "Vlc_player" : {
        "enabled" : false,
        "volume" : 100,
        "bin_path"   : "/bin/sh"
    },

    "Mpd_player" : {
        "enabled" : true,
        "debug" : false,
        "run_mpd" : true,
        "bin_path" : "/bin/sh",
        "socket" : "/run/systemd/notify",
        "host" : "localhost",
        "port" : 6600,
        "volume" : 100
    },

    "Sdr_player" : {
        "enabled" : true,
        "bin_path"  : "/bin/sh",
        "work_conf"  : "/etc/hosts",
        "gold_conf"  : "/etc/hosts",
        "low_s"      : -20.0,
        "low_low_s"  : -40.0
    },

    "Ogg_player" : {
        "enabled" : true,
        "device_type" : "alsa",
        "bin_path"   : "/bin/sh"
    },

    "Mp3_player" : {
        "enabled" : false,
        "device_type" : "alsa",
        "bin_path"   : "/bin/sh"
    }
    
}

=== farlies/rsked/test/tconfig.json
{
    "encoding"   : "UTF-8",
    "schema" : "1.2",

    "General" : {
        "application" : "rsked",
        "sched_path" : "~/.config/rsked/schedule.json",
        "version" : "2022-03-30T17:19:00",
	"description" : "tconfig.json is used for unit tests--not schema conformant"
    },
    
    "Mpd_player" : {
        "enabled" : true,
	"bin_path" : "/bin/sh",
        "socket" : "/run/systemd/notify",
        "host" : "localhost",
        "port" : 6666
    },

    "player_preference" : {
        "radio" : {
            "wfm" : [ "Sdr_player" ],
            "nfm" : [ "Cubic_player", "Sdr_player" ]
        },
        "stream" : {
            "mp3" : [ "Vlc_player", "Mpd_player", "Mp3_player" ],
            "mp4" : [ "Vlc_player", "Mpd_player" ],
            "ogg" : [ "Ogg_player", "Vlc_player" ]
        }
    },

    "Sdr_player" : {
        "enabled" : true,
	"description" : "should throw since work path shouldn't exist while gold should",
        "bin_path"  : "~/bin/gqrx",
        "gold_conf"  : "/tmp/noexist-gqrx.conf",
        "work_conf"  : "/etc/hosts",
        "low_s"      : -20.0,
        "low_low_s"  : -40.0
    },

    "Ogg_player" : {
        "enabled" : true,
        "bin_path"   : "/bin/sh"
    },

    "Mp3_player" : {
        "enabled" : false,
        "device_type" : "alsa",
        "bin_path"   : "/bin/sh"
    }
}
