=== farlies/rsked/scripts/rsked_schema-1.1.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://rsked.org/rsked_schema1.json",
    "title": "rsked-1.1",
    "description": "Validates an rsked configuration written in JSON with schema 1.1",
    "type": "object",
    "required": [ "encoding", "schema" ],
    "additionalProperties" : false,
    "properties": {
        "encoding": { "const": "UTF-8" },
        "schema": { "const": "1.1" },
        "General" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "application" : { "type" : "string" },
                "version" : {"type" : "string" },
                "description" : {"type" : "string" },
                "sched_path" : {"type" : "string" }
            }
        },
        "Inet_checker" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "refresh" : {"type" : "integer", "minimum" : 10 }
            }
        },
        "VU_monitor" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "timeout" : {"type" : "integer", "minimum" : 10 },
                "vu_bin_path" : {"type" : "string" }
            }
        },
        "Mpd_player" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "debug" : {"type" : "boolean" },
                "run_mpd" : {"type" : "boolean" },
                "bin_path" : {"type" : "string" },
                "socket" : {"type" : "string" },
                "host" : {"type" : "string" },
                "port" : {"type" : "integer", "minimum" : 1 },
                "volume" : {"type" : "integer", "minimum" : 0, "maximum" : 100 }
            }
        },
        "Sdr_player" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "gqrx_bin_path" : {"type" : "string" },
                "gqrx_work" : {"type" : "string" },
                "gqrx_gold" : {"type" : "string" },
                "low_s" : {"type" : "number" },
                "low_low_s" : {"type" : "number" },
                "device_vendor" : {
                    "type" : "string",
                    "pattern" : "^[0-9A-Fa-f]{4}$"
                },
                "device_product" : {
                    "type" : "string",
                    "pattern" : "^[0-9A-Fa-f]{4}$"
                }
            }
        },
        "Vlc_player" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "debug" : {"type" : "boolean" },
                "wait_us" : {"type" : "integer", "minimum" : 100 },
                "bin_path" : {"type" : "string" },
                "volume" : {"type" : "integer", "minimum" : 0, "maximum" : 100 }
            }
        },
        "Nrsc5_player" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "device_index" : {"type" : "integer", "minimum" : 0 },
                "nrsc5_bin_path" : {"type" : "string" }
            }
        },
        "Ogg_player" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "device_type" : {"enum" : ["alsa","pulse"] },
                "ogg_bin_path" : {"type" : "string" }
            }
        },
        "Mp3_player" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "enabled" : {"type" : "boolean" },
                "mp3_bin_path" : {"type" : "string" },
                "device_type" : {"enum" : ["alsa","oss"] }
            }
        },
        "player_preference" : {
            "type" : "object",
            "additionalProperties" : false,
            "properties" : {
                "playlist" : {"type" : "object" },
                "directory" : {"type" : "object" },
                "file" : {"type" : "object" },
                "radio" : {"type" : "object" },
                "stream" : {"type" : "object" }
            }
        }
    }
}

=== farlies/rsked/test/vlc.json
{
    "encoding"   : "UTF-8",
    "schema" : "1.1",

    "General" : {
        "application" : "rsked",
        "sched_path" : "~/.config/rsked/schedule.json",
        "version" : "2020-12-27T11:44",
        "description" : "for vlc testing"
    },

   "Vlc_player" : {
        "enabled" : true,
        "debug" : true,
        "bin_path" : "/usr/bin/vlc",
        "volume" : 100
    }
}

=== farlies/rsked/config/example-armv7l/rsked/example-rsked.json
{
    "encoding" : "UTF-8",
    "schema" : "1.1",

    "General" : {
        "application" : "rsked",
        "sched_path" : "~/.config/rsked/schedule.json",
        "version" : "2021-01-18T18:00",
        "description" : "example for 32-bit RPi Linux"
    },

    "Inet_checker" : {
        "enabled" : true,
        "refresh" : 60
    },

    "VU_monitor" : {
        "enabled" : true,
        "vu_bin_path" : "~/bin/vumonitor",
        "timeout" : 40
    },

    "Vlc_player" : {
        "enabled" : false,
        "debug" : false,
        "bin_path" : "/usr/bin/vlc",
        "volume" : 100
    },

    "Mpd_player" : {
        "enabled" : true,
        "debug" : false,
        "run_mpd" : true,
        "bin_path" : "/usr/bin/mpd",
        "socket" : "/run/user/1000/mpd.socket",
        "host" : "localhost",
        "port" : 6600,
        "volume" : 75
    },

    "Nrsc5_player" : {
        "enabled" : true,
        "nrsc5_bin_path"  : "~/bin/nrsc5",
        "device_index" : 0
    },

    "Sdr_player" : {
        "enabled" : true,
        "gqrx_bin_path"  : "~/bin/gqrx",
        "gqrx_work"  : "~/.config/gqrx/gqrx.conf",
        "gqrx_gold"  : "~/.config/gqrx/gold.conf",
        "low_s"      : -20.0,
        "low_low_s"  : -40.0,
        "device_vendor" : "0bda",
        "device_product" : "2838"
    },

    "Ogg_player" : {
        "enabled" : true,
        "device_type" : "pulse",
        "ogg_bin_path"   : "/usr/bin/ogg123"
    },

    "Mp3_player" : {
        "enabled" : true,
        "device_type" : "alsa",
        "mp3_bin_path"   : "/usr/bin/mpg321"
    }
}
