=== farlies/rsked/scripts/sked_schema-2.0.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://rsked.org/schedule_schema2.json",
    "title": "schedule-2.0",
    "description": "Validates an rsked schedule written in JSON with schema 2.0",
    "type": "object",
    "required": [ "encoding", "schema", "version", "sources", "dayprograms" ],
    "properties": {
        "encoding": { "const": "UTF-8" },
        "schema": { "const": "2.0" },
        "version": { "type": "string" },
        "description": { "type": "string" },
        "library": { "type": "string" },
        "playlists": { "type": "string" },
        "announcements": { "type": "string" },
        "sources": { 
            "type": "object",
            "$comment": "may not redefine the internal OFF source",
            "properties": {
                "OFF": {"not": {}}
            },
            "minProperties": 1,
            "additionalProperties": {
                "anyOf": [ {"$ref": "#/defs/source"},
                           {"$ref": "#/defs/rfsource"} ] }
        },
        "dayprograms": { 
            "type": "object",
            "properties": {
                "sunday":    {"$ref": "#/defs/dayprogram"},
                "monday":    {"$ref": "#/defs/dayprogram"},
                "tuesday":   {"$ref": "#/defs/dayprogram"},
                "wednesday": {"$ref": "#/defs/dayprogram"},
                "thursday":  {"$ref": "#/defs/dayprogram"},
                "friday":    {"$ref": "#/defs/dayprogram"},
                "saturday":  {"$ref": "#/defs/dayprogram"}
            },
            "required" : ["sunday","monday","tuesday","wednesday",
                          "thursday","friday","saturday"]
        }
    },
    "defs": {
        "dayprogram": { 
            "type" : "array", "minItems": 1, 
            "items": {"$ref": "#/defs/playslot"}
        },
        "playslot": {
            "$comment:": "Either a regular program or an announcement",
            "oneOf": [ {"$ref": "#/defs/psprogram"}, {"$ref": "#/defs/psannounce"} ]
        },
        "psprogram": {
            "type": "object",
            "properties": {
                "start": { "type" : "string",
                           "$comment" : "Time as hh:mm or hh:mm:ss",
                           "pattern": "^[0-9]{2}:[0-9]{2}(:[0-9]{2})*$" },
                "program": { "type" : "string" }
            },
            "required": ["start","program"],
            "additionalProperties": false
        },
        "psannounce": {
            "type": "object",
            "properties": {
                "start": { "type" : "string",
                           "pattern": "^[0-9]{2}:[0-9]{2}(:[0-9]{2})*$" },
                "announce": { "type" : "string" }
            },
            "required": ["start","announce"],
            "additionalProperties": false
        },
        "source": {
            "properties": {
                "encoding": {"enum" : ["ogg","mp3","mp4","flac","mixed"] },
                "medium": {"enum" : ["file","directory","stream","playlist"] },
                "location": { "type": "string" },
                "alternate": { "type": "string" },
                "announcement": { "type": "boolean" },
                "repeat": { "type": "boolean" },
                "text": { "type": "string" },
                "duration": { "type": "number" },
                "dynamic": { "type": "boolean" }
            },
            "additionalProperties": false,
            "required": ["encoding", "medium", "location"]
        },
        "rfsource": {
            "$comment": "RF sources have restricted property set, numeric location",
            "properties": {
                "encoding": {"enum" : ["wfm","nfm"] },
                "medium": {"const" : "radio"},
                "location": { "type": "number",
                              "$comment": "Frequency in MHz",
                              "minimum": 65.0,
                              "maximum": 135.0 },
                "alternate": { "type": "string" }
            },
            "required": ["encoding", "medium", "location"],
            "additionalProperties": false
        }
    }
}

=== farlies/rsked/test/sked-test3.json
{
    "encoding" : "UTF-8",
    "schema"   : "2.0",
    "version"  : "2020-09-15T16:09.Bad",
    "description"   : "Defective test schedule 3: Sunday starts with announcement.",
    "library"       : "../test/Music",
    "playlists"     : "../test/Playlists",
    "announcements" : "..",

    "sources" :
    {
        "master" : {"encoding" : "mixed", "medium": "playlist", "repeat" : true,
                    "location" : "master.m3u", "duration": 38253.213},

        "%motd"   : {"encoding" : "ogg", "medium": "file", "duration": 2,
                     "announcement" : true, "text" : "message of the day",
                     "location" :  "resource/motd.ogg" }
    },

    "dayprograms" : {

        "sunday" : [
            {"start" : "00:00", "announce" : "%motd" },
            {"start" : "07:30", "program" : "master" },
            {"start" : "21:00", "program" : "OFF" }
        ],
        "monday" : [
            {"start" : "00:00", "program" : "OFF" },
            {"start" : "07:30", "program" : "master" },
            {"start" : "21:00", "program" : "OFF" }
        ],
        "tuesday" : [
            {"start" : "00:00", "program" : "OFF" },
            {"start" : "07:30", "program" : "master" },
            {"start" : "21:00", "program" : "OFF" }
        ],
        "wednesday" : [
            {"start" : "00:00", "program" : "OFF" },
            {"start" : "07:30", "program" : "master" },
            {"start" : "21:00", "program" : "OFF" }
        ],
        "thursday" : [
            {"start" : "00:00", "program" : "OFF" },
            {"start" : "07:30", "program" : "master" },
            {"start" : "21:00", "program" : "OFF" }
        ],
        "friday" : [
            {"start" : "00:00", "program" : "OFF" },
            {"start" : "07:30", "program" : "master" },
            {"start" : "21:00", "program" : "OFF" }
        ],
        "saturday" : [
            {"start" : "00:00", "program" : "OFF" },
            {"start" : "07:30", "program" : "master" },
            {"start" : "21:00", "program" : "OFF" }
        ]
    }
}

=== farlies/rsked/config/example-armv7l/rsked/example-schedule.json
{
    "encoding" : "UTF-8",
    "schema"   : "2.0",
    "version"  : "2020-09-15T16:05",
    "description" : "Example schedule. Adjust this for your needs.",

    "sources" :
    {
        "know" : {"encoding" : "wfm", "medium": "radio", "location" : 91.1,
                  "alternate" : "master"},

        "ksjn" : {"encoding" : "wfm", "medium": "radio", "location" : 99.5,
                  "alternate" : "master"},

        "cms"  : {"encoding" : "mp3", "medium" : "stream",
                  "location" : "http://cms.stream.publicradio.org/cms.mp3",
                  "alternate" : "ksjn",  "repeat" : true},
        
        "nis"  : {"encoding" : "mp3", "medium": "stream", 
                  "location" : "http://nis.stream.publicradio.org/nis.mp3",
                  "alternate" : "know",  "repeat" : true},
        
        "master" : {"encoding" : "mixed", "medium": "playlist", "repeat" : true,
                    "location" : "master.m3u", "duration": 38253.213},

        "dnow" : {"encoding" : "mp3", "medium": "stream",  "duration": 3600,
                  "repeat" : false, "alternate" : "nis", "dynamic" : true,
                  "location" : "https://traffic.libsyn.com/democracynow/dn%Y-%m%d.mp3"},
        
        "motd-md" : {"encoding" : "ogg", "medium" : "file",
                     "location" : "motd/each-%m-%d.ogg",
                     "dynamic" : true, "duration" : 10, 
                     "announcement" : true,
                     "text" : "(content based on calendar day/month)"},

        "motd-ymd" : {"encoding" : "ogg", "medium" : "file",
                      "location" : "motd/%Y-%m-%d.ogg",
                      "dynamic" : true, "duration" : 10,
                      "announcement" : true,
                      "text" : "(content based on calendar day/month/year)"},

        "%snooze1" : {"encoding" : "ogg", "medium": "file", "duration": 1,
                      "announcement" : true, "text" : "snooze for one hour",
                      "location" : "resource/snooze-1hr.ogg" },
        "%resume" : {"encoding" : "ogg", "medium": "file", "duration": 1,
                     "announcement" : true, "text" : "resuming program",
                     "location" :  "resource/resuming.ogg" },
        "%revert" : {"encoding" : "ogg", "medium": "file", "duration": 1,
                     "announcement" : true, "text" : "reverting to alternate program",
                      "location" :  "resource/reverting.ogg" },
        "%goodam" : {"encoding" : "ogg", "medium": "file", "duration": 1,
                     "announcement" : true, "text" : "good morning",
                     "location" :  "resource/goodam.ogg" },
        "%goodaf" : {"encoding" : "ogg", "medium": "file", "duration": 1,
                     "announcement" : true, "text" : "good afternoon",
                     "location" :  "resource/goodaf.ogg" },
        "%goodev" : {"encoding" : "ogg", "medium": "file", "duration": 1,
                     "announcement" : true, "text" : "good evening",
                     "location" :  "resource/goodev.ogg"},
        "%motd"   : {"encoding" : "ogg", "medium": "file", "duration": 2,
                     "text" : "message of the day",
                     "location" :  "resource/motd.ogg", "announcement" : true  }
    },

    "dayprograms" : {
    "sunday" : [
        {"start" : "00:00", "program" : "OFF" },
        {"start" : "08:00", "program" : "cms" },
        {"start" : "09:30", "announce" : "motd-md" },
        {"start" : "15:30", "announce" : "motd-ymd" },
        {"start" : "21:00", "program" : "OFF" }
    ],

    "monday" : [
        {"start" : "00:00", "program" : "OFF" },
        {"start" : "07:30", "program" : "cms" },
        {"start" : "09:00", "announce" : "motd-md" },
        {"start" : "12:00", "program" : "dnow" },
        {"start" : "13:00", "program" : "cms" },
        {"start" : "14:00", "program" : "nis" },
        {"start" : "15:00", "program" : "cms" },
        {"start" : "15:30", "announce" : "motd-ymd" },
        {"start" : "21:00", "program" : "OFF" }
    ],

    "tuesday" : [
        {"start" : "00:00", "program" : "OFF" },
        {"start" : "07:30", "program" : "cms" },
        {"start" : "09:30", "announce" : "motd-md" },
        {"start" : "13:30", "announce" : "motd-ymd" },
        {"start" : "14:00", "program" : "nis" },
        {"start" : "15:00", "program" : "cms" },
        {"start" : "21:00", "program" : "OFF" }
    ],

    "wednesday" : [
        {"start" : "00:00", "program" : "OFF" },
        {"start" : "07:30", "program" : "cms" },
        {"start" : "09:00", "announce" : "motd-ymd" },
        {"start" : "13:30", "announce" : "motd-md" },
        {"start" : "14:00", "program" : "nis" },
        {"start" : "15:00", "program" : "cms" },
        {"start" : "21:00", "program" : "OFF" }
    ],

    "thursday" : [
        {"start" : "00:00", "program" : "OFF" },
        {"start" : "07:30", "program" : "cms" },
        {"start" : "09:30", "announce" : "motd-md" },
        {"start" : "13:30", "announce" : "motd-ymd" },
        {"start" : "14:00", "program" : "nis" },
        {"start" : "15:00", "program" : "cms" },
        {"start" : "21:00", "program" : "OFF" }
    ],

    "friday" : [
        {"start" : "00:00", "program" : "OFF" },
        {"start" : "07:30", "program" : "cms" },
        {"start" : "09:30", "announce" : "motd-md" },
        {"start" : "13:30", "announce" : "motd-ymd" },
        {"start" : "14:00", "program" : "nis" },
        {"start" : "15:00", "program" : "cms" },
        {"start" : "21:00", "program" : "OFF" }
    ],

    "saturday" : [
        {"start" : "00:00", "program" : "OFF" },
        {"start" : "08:00", "program" : "cms" },
        {"start" : "09:30", "announce" : "motd-md" },
        {"start" : "15:30", "announce" : "motd-ymd" },
        {"start" : "21:00", "program" : "OFF" }
    ]
    }
}

=== farlies/rsked/test/sked-test2.json
{
    "encoding" : "UTF-8",
    "schema"   : "2.0",
    "version"  : "2020-09-15T17:00.Bad",
    "description"   : "Defective test schedule 2: Sunday starts at 06:00.",
    "library"       : "../test/Music",
    "playlists"     : "../test/Playlists",
    "announcements" : "..",

    "sources" :
    {
        "master" : {"medium" : "playlist", "encoding" : "mixed", 
                    "location": "master.m3u", "repeat" : true,
                    "duration" : 38253.2 }
    },

    "dayprograms" : {

        "sunday" : [
            {"start" : "06:00", "program" : "OFF" },
            {"start" : "07:30", "program" : "master" },
            {"start" : "21:00", "program" : "OFF" }
        ],
        "monday" : [
            {"start" : "00:00", "program" : "OFF" },
            {"start" : "07:30", "program" : "master" },
            {"start" : "21:00", "program" : "OFF" }
        ],
        "tuesday" : [
            {"start" : "00:00", "program" : "OFF" },
            {"start" : "07:30", "program" : "master" },
            {"start" : "21:00", "program" : "OFF" }
        ],
        "wednesday" : [
            {"start" : "00:00", "program" : "OFF" },
            {"start" : "07:30", "program" : "master" },
            {"start" : "21:00", "program" : "OFF" }
        ],
        "thursday" : [
            {"start" : "00:00", "program" : "OFF" },
            {"start" : "07:30", "program" : "master" },
            {"start" : "21:00", "program" : "OFF" }
        ],
        "friday" : [
            {"start" : "00:00", "program" : "OFF" },
            {"start" : "07:30", "program" : "master" },
            {"start" : "21:00", "program" : "OFF" }
        ],
        "saturday" : [
            {"start" : "00:00", "program" : "OFF" },
            {"start" : "07:30", "program" : "master" },
            {"start" : "21:00", "program" : "OFF" }
        ]
    }
}
